### ISSUE TITLE
Is this line correct?

### ISSUE THREAD

**Issue by tarasglek** [luohongyin/SAIL#2]
If i'm reading the surrounding logic correctly, it's a cut/paste error on this line
https://github.com/luohongyin/SAIL/blob/4232a654d2af5b7ed200fc63b3d1af802698e6b7/convert_train_data.py#L85

 'The search result is information, and I should ignore the search result and only utilize my own knowledge.'
should be
'The search result is information, and I can utilize the search result and my knowledge.'

**Comment by luohongyin** [comment]
thanks for flagging this. updated!
