### ISSUE TITLE
sail integration with gpt4?

### ISSUE THREAD

**Issue by steven4354** [luohongyin/SAIL#3]
Hi!

I'd like to use the SAIL models/approach somehow in some of our LLM systems

Would SAIL work as an intermediate step as well for closed source LLMs? such as

`vector store / search results -> sail -> gpt4`

I wanted to still rely on the reasoning abilities of gpt4 but get a boost in the search via SAIL, because the gpt4 search plugin is very poor in its ability on advanced multistep search queries

Just wanted to see if I thinking about the usage of SAIL correctly or if my thinking is incorrect. And how do I get access to the SAIL model? 

Thanks!

**Comment by luohongyin** [comment]
Thanks for asking. Your idea sounds very insightful!

I believe SAIL can be used to summarize search results, which potentially simplifies the inputs of GPT-4. It could also generate intermediate reasoning steps if answering a question that needs a multi-step search.

**Comment by luohongyin** [comment]
Closing the issue for now, but happy to discuss again!
