### ISSUE TITLE
Training LLM without reasoning

### ISSUE THREAD

**Issue by TccccD** [luohongyin/SAIL#4]
Great work, I would like to ask if you have tried to train LLM without reasoning, and then compared it with LLM with reasoning. Because we can't use gpt4 here, we can't generate reasoning.
The reasoning I refer to is the process of selecting information in the response

Search result (1) is distracting, search result
(2) is informative, and search result (3) is
distracting. i will utilize the informative search
result (2) and my knowledge. **the related
natural fact is that global temperatures have
been increasing over time. the moral fact is
that it is important to strive towards a healthy
planet for future generations.**

@luohongyin

**Comment by luohongyin** [comment]
For instruction following, I used this corpus: https://github.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM. They use an Apache-2.0 license so hopefully other organizations could use as well.

The reasoning sequence (information selection) is not generated by gpt4 - its "generated" (actually constructed) with a 350M textual entailment model that would be automatically downloaded with my code from Huggingface.

**Comment by TccccD** [comment]
> For instruction following, I used this corpus: https://github.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM. They use an Apache-2.0 license so hopefully other organizations could use as well.
> 
> The reasoning sequence (information selection) is not generated by gpt4 - its "generated" (actually constructed) with a 350M textual entailment model that would be automatically downloaded with my code from Huggingface.


I looked at your code, and I found that the textual entailment model is only generated to this part

```
Search result (1) is distracting, search result
(2) is informative, and search result (3) is
distracting. i will utilize the informative search
result (2) and my knowledge.
```

but this part of the description is not generated, right?

```
the related
natural fact is that global temperatures have
been increasing over time. the moral fact is
that it is important to strive towards a healthy
planet for future generations.

```

**Comment by luohongyin** [comment]
Right, the second part is the labeled response. In my case it's generated by GPT4, but it could be generated by any stronger models or human annotators.
