### ISSUE TITLE
Instruction to install the pre-trained model locally

### ISSUE THREAD

**Issue by pexus** [luohongyin/SAIL#6]
Hello  - Can the pre-trained model with search augmentation be installed locally? Will you be providing instructions for that any time soon?  Thank you.

**Comment by luohongyin** [comment]
Hi, Thanks for asking!

The model can be loaded locally via
```python
from transformers import AutoTokenizer, LlamaForCausalLM

tokenizer = AutoTokenizer.from_pretrained('luohy/SAIL-7b')
model = LlamaForCausalLM.from_pretrained('luohy/SAIL-7b')
```

Please feel free to let me know if there is any problem!
